build: move Node release process to release-please
googleapis/releasetool pull request #311
Opened 2021-03-25 23:58 UTC by sofisl

2021-03-26 00:30 UTC, bcoe requested changes
Caught a few minor things (_we're victims of having no test coverage for this._)

Thanks for the patch.

2021-03-26 00:30 UTC, bcoe commented on releasetool/commands/tag/nodejs.py
>          repo = ctx.release_pr["base"]["repo"]["full_name"]
I believe we'll need to pull this above the `if` so that it can be used in the other block.

2021-03-26 00:30 UTC, bcoe commented on releasetool/commands/tag/nodejs.py
> +                f"--token={token_file}",
likewise, the `token_file` logic is in the first if, just need to pul up.

2021-03-26 00:30 UTC, bcoe commented on releasetool/commands/tag/nodejs.py
> +                "--debug",
I believe `--debug` can accidentally leak secrets in logs, so probably good to drop.

2021-03-26 00:30 UTC, bcoe commented on releasetool/commands/tag/nodejs.py
> +                f"--package-name={ctx.release_version}"
you can just get rid of `--package-name`, `releaae-please` will automatically grab it from `package.json`.

2021-04-06 20:59 UTC, bcoe approved these changes
This looks good to me, but could I bother you to test it out in fusion before we merge.

Let me know if you want a walkthrough on how to do so, basically:

1. you find the job in fusion.
2. you run the job manually, pointing at your branch rather than the main branch.

We would need to do test this after merging a library we expect to have a release created for.

2021-09-14 16:29 UTC, chingor13 commented
Closing this as we switched to release-please tagging in https://github.com/googleapis/synthtool/pull/1129

2021-09-14 16:29 UTC, closed without merging